In [69]:
import pandas as pd

In [77]:
path = 'data/01.json'
with open(path, encoding="utf8") as file: 
    content = file.read()
parsed = json.loads(content)  
#pop first layer of the records
parsed.update(parsed.pop('records'))

In [84]:
df = pd.DataFrame.from_dict(parsed, orient='index')

In [101]:
#Subject Access fields
df.filter(regex=("^6.*"))

,610,648,689,600,650,651,655,688,630,653,611
BV000023649,"{'a': 'Deutsches Literaturarchiv Marbach', '0'...","{'a': 'Geschichte', '2': 'gnd', '9': 'rswk-swf'}",{'5': 'DE-604'},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BV000024214,NaN,"{'a': 'Geschichte 1830-1848', '2': 'gnd', '9':...",{'5': 'DE-604'},"{'a': 'Burckhardt, Jacob', 'd': '1818-1897', '...","{'a': 'Kunstbetrachtung', '0': '(DE-588)412532...","{'a': 'Deutschland', '0': '(DE-588)4011882-4',...",NaN,NaN,NaN,NaN,NaN
BV000024767,NaN,"{'a': 'Weltgeschichte', '2': 'gnd', '9': 'rswk...","{'8': '5|p', '5': 'DE-604'}","{'a': 'Burckhardt, Jacob', 'd': '1818-1897', '...","{'a': 'Weltgeschichte', '0': '(DE-588)4079158-...",NaN,"{'0': '(DE-588)4143413-4', 'a': 'Aufsatzsammlu...","{'a': 'Jacob Burckhardt (1818 - 1897)', '0': '...",NaN,NaN,NaN
BV000025578,NaN,NaN,{'5': 'DE-604'},"{'a': 'Herzog, Werner', 'd': '1942-', '0': '(D...",{'a': 'German fiction'},NaN,NaN,NaN,"{'a': 'Fitzcarraldo', '0': '(DE-588)4154490-0'...",NaN,NaN
BV000026429,NaN,NaN,{'5': 'DE-604'},"{'a': 'Rauzzini, Filippo', '0': '(DE-588)12110...","{'a': 'Architecture, Rococo', 'z': 'Italy'}",{'a': 'Italien'},"{'0': '(DE-588)4016928-5', 'a': 'Festschrift',...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
BV001554556,NaN,NaN,NaN,NaN,{'a': 'Geschichte'},"{'a': 'Terni (Italy)', 'x': 'History'}",NaN,NaN,NaN,NaN,NaN
BV001554561,NaN,NaN,NaN,NaN,NaN,{'a': 'Rieti (Italy)'},NaN,NaN,NaN,NaN,NaN
BV001554563,NaN,"{'a': 'Geschichte 1250-1816', '2': 'gnd', '9':...",{'5': 'DE-604'},NaN,NaN,"{'a': 'Arezzo', '0': '(DE-588)4002888-4', '2':...",NaN,NaN,NaN,NaN,NaN
BV001554686,"{'a': 'Basilica palladiana (Vicenza, Italy)'}","{'a': 'Geschichte -1580', '2': 'gnd', '9': 'rs...","{'C': 'b', '5': 'DE-604'}","{'a': 'Palladio, Andrea', 'd': '1508-1580', '0...","{'a': 'Architekturtheorie', '0': '(DE-588)4112...","{'a': 'Vicenza', '0': '(DE-588)4063445-0', '2'...",NaN,NaN,NaN,"{'a': 'Palladio, Andrea'}",NaN
BV001555100,NaN,NaN,{'5': 'DE-604'},NaN,"{'a': 'Kunstkritik', '0': '(DE-588)4033659-1',...",NaN,NaN,NaN,NaN,NaN,NaN

In [195]:
df['648'].astype(str).str.extract(r'(?<=\'a\':\s\')(.*?)(?=\')')

                                0
BV000023649            Geschichte
BV000024214  Geschichte 1830-1848
BV000024767        Weltgeschichte
BV000025578                   NaN
BV000026429                   NaN
...                           ...
BV001554556                   NaN
BV001554561                   NaN
BV001554563  Geschichte 1250-1816
BV001554686      Geschichte -1580
BV001555100                   NaN

[6008 rows x 1 columns]

### List of columns that we might be interested in
041: 'language_code'  
049: 'holdings'  
100: 'author_person'    
110: 'author_corporate'  
245: 'title'  
264: 'publication'  
300: 'physical_description'  
600: 'subject_personal'  
611: 'subject_corporate'  
648: 'subject_chronological'  
650: 'subject_topical'  
keep all the 6XX for topics